USE lib;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS BorrowingRecord;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Users;

SET FOREIGN_KEY_CHECKS = 1;
